import type { InsertBrokerConfig } from "../schema/06-08-portfolio-execution.js";

export const BROKER_SEEDS: InsertBrokerConfig[] = [
  {
    brokerId: "easyequities",
    displayName: "EasyEquities",
    commissionPct: "0.002500",
    commissionMinZar: null,
    hasMonthlyFlatFee: true,
    monthlyFlatFeeZar: "25.00",
    thriveWaiverUnderAge: 21,
    thriveWaiverOverAge: 65,
    fractionalShares: true,
    minTradeZar: "5.00",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    notes: "Thrive fee waived: under 21, over 65, or Thrive Level 3. ZAR account only.",
  },
  {
    brokerId: "satrix_direct",
    displayName: "Satrix Direct",
    commissionPct: "0.002000",
    commissionMinZar: null,
    hasMonthlyFlatFee: false,
    monthlyFlatFeeZar: null,
    thriveWaiverUnderAge: null,
    thriveWaiverOverAge: null,
    fractionalShares: false,
    minTradeZar: "10.00",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    notes: "No monthly fee. No fractional shares. Recommended for capital < R2,000.",
  },
  {
    brokerId: "capitec_invest",
    displayName: "Capitec Invest",
    commissionPct: "0.005000",
    commissionMinZar: null,
    hasMonthlyFlatFee: false,
    monthlyFlatFeeZar: null,
    thriveWaiverUnderAge: null,
    thriveWaiverOverAge: null,
    fractionalShares: false,
    minTradeZar: "10.00",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    notes: null,
  },
  {
    brokerId: "standard_bank_ost",
    displayName: "Standard Bank Online Share Trading",
    commissionPct: "0.005500",
    commissionMinZar: "79.00",
    hasMonthlyFlatFee: false,
    monthlyFlatFeeZar: null,
    thriveWaiverUnderAge: null,
    thriveWaiverOverAge: null,
    fractionalShares: false,
    minTradeZar: "100.00",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    notes: "R79 minimum commission per trade.",
  },
  {
    brokerId: "fnb",
    displayName: "FNB Share Investing",
    commissionPct: "0.005500",
    commissionMinZar: "70.00",
    hasMonthlyFlatFee: false,
    monthlyFlatFeeZar: null,
    thriveWaiverUnderAge: null,
    thriveWaiverOverAge: null,
    fractionalShares: false,
    minTradeZar: "100.00",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    notes: "R70 minimum commission per trade.",
  },
];
