export const COST_MODEL_PARAMETER_SEEDS = [
  {
    parameter: "stt_rate",
    value: "0.002500",
    unit: "fraction",
    effectiveFrom: "2008-02-01",
    effectiveTo: null,
    rationale: "Securities Transfer Tax — applied to all equity purchases only",
    source: "SARS",
  },
  {
    parameter: "dividend_withholding_tax_rate",
    value: "0.200000",
    unit: "fraction",
    effectiveFrom: "2017-02-22",
    effectiveTo: null,
    rationale: "Dividend Withholding Tax on all dividend distributions",
    source: "SARS",
  },
  {
    parameter: "cgt_effective_rate_corporate",
    value: "0.216000",
    unit: "fraction",
    effectiveFrom: "2023-03-01",
    effectiveTo: null,
    rationale: "80% inclusion × 27% corporate tax rate",
    source: "SARS",
  },
  {
    parameter: "cgt_effective_rate_individual_max",
    value: "0.180000",
    unit: "fraction",
    effectiveFrom: "2023-03-01",
    effectiveTo: null,
    rationale: "40% inclusion × 45% marginal tax rate",
    source: "SARS",
  },
  {
    parameter: "cgt_annual_exclusion_individual_zar",
    value: "50000.000000",
    unit: "zar",
    effectiveFrom: "2026-02-26",
    effectiveTo: null,
    rationale: "Annual CGT exclusion per individual — SARS Budget 26 Feb 2026 (was R40,000)",
    source: "SARS Budget 2026",
  },
  {
    parameter: "adtv_capacity_fraction",
    value: "0.050000",
    unit: "fraction",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    rationale: "Maximum position size as fraction of 20-day ADTV to limit market impact",
    source: "internal",
  },
  {
    parameter: "market_impact_k",
    value: "0.100000",
    unit: "dimensionless",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    rationale: "Square-root market impact model coefficient k. Estimated from Almgren et al.",
    source: "Almgren et al.",
  },
];
